apiVersion: apps/v1
kind: Deployment
metadata:
  name: okxeel-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okxeel
  template:
    metadata:
      labels:
        app: okxeel
    spec:
      containers:
        - name: okxeel
          image: bucha1958/okxeel:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: okxeel-config
---
apiVersion: v1
kind: Service
metadata:
  name: okxeel-service
spec:
  selector:
    app: okxeel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: okxeel-ingress
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: okxeel-service
              port:
                number: 80
        - path: /api/auth
          pathType: Prefix
          backend:
            service:
              name: auth-service
              port:
                number: 4000
        - path: /api/products
          pathType: Prefix
          backend:
            service:
              name: general-service
              port:
                number: 3000
