name: Okxeel Service CI

on:
  push:
    paths:
      - 'OkxeelFashion/**'

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set commit date as image tag
        id: tag
        run: |
          DATE_TAG=$(date -u +"%Y-%m-%d-%H%M")
          echo "tag=$DATE_TAG" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and tag Docker image
        run: |
          cd auth-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/okxeel:latest -t ${{ secrets.DOCKER_USERNAME }}/okxeel:${{ steps.tag.outputs.tag }} .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/okxeel:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/okxeel:${{ steps.tag.outputs.tag }}
